INSERT INTO countries (
    iso2_code,
    iso3_code,
    name,
    region,
    income_group,
    active
)
VALUES
    ('TR', 'TUR', 'Türkiye', 'Europe', 'Upper middle income', TRUE),
    ('PL', 'POL', 'Poland', 'Europe', 'High income', TRUE),
    ('RO', 'ROU', 'Romania', 'Europe', 'High income', TRUE),
    ('DE', 'DEU', 'Germany', 'Europe', 'High income', TRUE),
    ('FR', 'FRA', 'France', 'Europe', 'High income', TRUE),
    ('IT', 'ITA', 'Italy', 'Europe', 'High income', TRUE),
    ('ES', 'ESP', 'Spain', 'Europe', 'High income', TRUE),
    ('NL', 'NLD', 'Netherlands', 'Europe', 'High income', TRUE),
    ('BE', 'BEL', 'Belgium', 'Europe', 'High income', TRUE),
    ('GB', 'GBR', 'United Kingdom', 'Europe', 'High income', TRUE),
    ('US', 'USA', 'United States', 'North America', 'High income', TRUE),
    ('CA', 'CAN', 'Canada', 'North America', 'High income', TRUE),
    ('MX', 'MEX', 'Mexico', 'North America', 'Upper middle income', TRUE),
    ('AE', 'ARE', 'United Arab Emirates', 'Middle East', 'High income', TRUE),
    ('SA', 'SAU', 'Saudi Arabia', 'Middle East', 'High income', TRUE),
    ('QA', 'QAT', 'Qatar', 'Middle East', 'High income', TRUE),
    ('EG', 'EGY', 'Egypt', 'Middle East', 'Lower middle income', TRUE),
    ('CN', 'CHN', 'China', 'Asia', 'Upper middle income', TRUE),
    ('JP', 'JPN', 'Japan', 'Asia', 'High income', TRUE),
    ('KR', 'KOR', 'South Korea', 'Asia', 'High income', TRUE),
    ('IN', 'IND', 'India', 'Asia', 'Lower middle income', TRUE),
    ('AU', 'AUS', 'Australia', 'Oceania', 'High income', TRUE),
    ('ZA', 'ZAF', 'South Africa', 'Africa', 'Upper middle income', TRUE),
    ('MA', 'MAR', 'Morocco', 'Africa', 'Lower middle income', TRUE),
    ('BR', 'BRA', 'Brazil', 'South America', 'Upper middle income', TRUE);