spring.application.name=exportpilot

# =========================
# Database
# =========================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# =========================
# Flyway
# =========================
spring.flyway.enabled=true

# =========================
# Spring Boot Actuator
# =========================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized

# =========================
# Swagger / OpenAPI
# =========================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.try-it-out-enabled=true

# =========================
# World Bank API
# =========================
world-bank.api.base-url=https://api.worldbank.org/v2
world-bank.api.source-name=World Bank
world-bank.api.per-page=100
world-bank.api.transformation-version=v1
world-bank.api.connect-timeout-seconds=10
world-bank.api.read-timeout-seconds=30


gemini.api.base-url=https://generativelanguage.googleapis.com/v1beta
gemini.api.key=${GEMINI_API_KEY:}
gemini.api.model=${GEMINI_MODEL:gemini-3.1-flash-lite}
gemini.api.max-output-tokens=1200


# UN Comtrade API
integrations.un-comtrade.base-url=https://comtradeapi.un.org
integrations.un-comtrade.api-key=${UN_COMTRADE_API_KEY:}